pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./acquire-office-365.html","Acquire Office 365","Enter topic text here.",""],
["./apply-metadata.html","Apply Metadata","Enter topic text here.",""],
["./connecting.html","OnePracticeSync &#62; Connecting","Enter topic text here.",""],
["./contatcs.html","Contacts","Enter topic text here.",""],
["./creating-a-template.html","Templates &#62; Creating Templates","Templates can be created in 2 ways - Online or on your desktop. ",""],
["./creating-documents-merging-tem.html","Templates &#62; Creating Documents: Merging Templates with Client or Job Data","Select the template you wish to use by clicking either the Client or Job logo to the right of the document in order to merge with the relevant dat...",""],
["./credentials.html","Credentials","Enter your Office 365 credentials on this screen in order to use the app.",""],
["./drag-and-drop.html","Templates &#62; The Controls &#62; Upload Templates","The Upload Templates button will open a new browser window and redirect you to the Modern Practice Templates folder. Here you can upload new Word ...",""],
["./field-tags.html","Templates &#62; Field Builder Options","There are 3 types of template fields: Standard, Custom and O365 User Info ",""],
["./first-run2.html","First Run","The first run of Scan Doctor will require you to enter the following:",""],
["./getting-started.html","Templates &#62; Getting Started","Templates is installed by default on the homepage of your SharePoint Document Center.",""],
["./help.html","Templates &#62; The Controls &#62; Help","A link to the software help website where you can download the complete Templates Documentation.",""],
["./help4.html","Help","Navigate to the software help website where you can download the complete Scan Doctor documentation.",""],
["./how-to-ocr-a-pdf.html","How to OCR a PDF","Once you have configured Scan Doctor, simply drag and drop your PDF/s into the Input Folder. Scan Doctor will automatically detect the file/s with...",""],
["./implement-tools-and-practices.html","Implement tools and practices","Enter topic text here.",""],
["./installation2.html","Installation","Go to https://software.hubone.com/scandoctor/ and click Download ScanDoctor.",""],
["./jobs.html","Jobs","Enter topic text here.",""],
["./license-onepractice.html","License OnePractice","Enter topic text here.",""],
["./mail-templates.html","Mail Templates","Enter topic text here.",""],
["./mail.html","Mail","Enter topic text here.",""],
["./metadata-and-templates.html","Templates &#62; Metadata and Templates","Please see our full user guide on metadata fields.",""],
["./modern-practice-templates-fold.html","Templates &#62; Creating Templates &#62; Part 3. Saving Templates &#62; Modern Practice Templates folder &#62; Online","Creating the template via the Modern Practice Template folder means your template will be saved as go. ",""],
["./onepractice-templates.html","Templates","Templates provides you with a central template store within your SharePoint Document Center so you can have a unified and consistent approach to w...",""],
["./onepracticesync.html","OnePracticeSync","OnePracticeSync was released in September 2020 and replaces previous functionality either directly connecting to Xero Practice Manager or using Mi...",""],
["./part-1_-creating-a-template.html","Templates &#62; Creating Templates &#62; Part 1. Creating New Templates","Creating from your Desktop Open Word or Excel on your PC. Move onto Part 2  Creating Online Open your preferred browser and navigate to your ...",""],
["./part-2_-adding-field-tags-to-y.html","Templates &#62; Creating Templates &#62; Part 2. Adding Field Tags to Templates","Add content to the document and style as desired. ",""],
["./process-history2.html","Process History","View a record of all activity conducted during your current use of the app.",""],
["./processed-documents.html","Processed Documents","View all processed documents on this screen.   Successfully processed: The most recent 100 successfully processed documents or documents that...",""],
["./provision-onepractice.html","Provision OnePractice","Enter topic text here.",""],
["./recently-saved-documents.html","Templates &#62; The Controls &#62; Recently Saved Documents","View recently saved documents and links to those files and the folder it was saved to in your Document Center.",""],
["./refresh.html","Templates &#62; The Controls &#62; Refresh","As Templates caches data locally in your internet browser to reduce network traffic and greatly speed up its functionality, it needs to be refresh...",""],
["./save-directly-into-modern-prac.html","Templates &#62; Creating Templates &#62; Part 3. Saving Templates &#62; Save directly into the Modern Practice Templates folder in the Document Center from Desktop","Within Word or Excel Desktop, go to File &#62; Save As.",""],
["./saving-templates.html","Templates &#62; Creating Templates &#62; Part 3. Saving Templates","Templates are saved differently depending on how they are created:",""],
["./scans.html","Scans","Enter topic text here.",""],
["./settings.html","Templates &#62; The Controls &#62; Settings","View essential settings retrieved from your SharePoint Document Center.",""],
["./settings4.html","Settings","Use this screen to update your input folder, output folder and output configuration.",""],
["./site-pages.html","Site Pages","Enter topic text here.",""],
["./staff.html","Staff","Enter topic text here.",""],
["./suppliers.html","Suppliers","Enter topic text here.",""],
["./tasks.html","Tasks","Enter topic text here.",""],
["./template-field-builder.html","Templates &#62; The Controls &#62; Template Field Builder","Create Standard, Custom Prompt and O365 User Info fields that you can easily copy and paste into your Microsoft Office template file.",""],
["./templates.html","Templates","Enter topic text here.",""],
["./the-controls.html","Templates &#62; The Controls","The controls can be accessed via icons at the top of the application.",""],
["./the-controls4.html","The Controls","The following are controls in Scan Doctor:  Credentials Processed Documents Settings Process History Help",""],
["./themes.html","Themes","OnePractice is SharePoint Theme enabled meaning if you change your theme in Office 365 SharePoint, it will reflect in the Templates, Mail and Mail...",""],
["./using-template-field-builder.html","Templates &#62; Using Template Field Builder","Standard Template Fields  The following steps show how to create a standard template field.  Select the type of field you want to use fr...",""],
["./verifying-a-template.html","Templates &#62; Verifying a Template","Once you have created your template, you should verify it against the rules used by the software. ",""],
["./word-for-desktop--save-to-desk.html","Templates &#62; Creating Templates &#62; Part 3. Saving Templates &#62; Save to Desktop &#62; Upload to Modern Practice Templates in your Document Center","Within Word or Excel Desktop, go to File &#62; Save As.",""]];
