pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./acquire-office-365.html","Acquire Office 365","Enter topic text here.",""],
["./add-sender-as-a-contact.html","Mail &#62; Add Sender as a Contact","Xero Practice Manager Users Only If you wish to add the email sender as a Contact in Xero Practice Manager for the Client you have selected, selec...",""],
["./adding-a-column-to-the-documen.html","Metadata &#62; Creating your own Metadata &#62; Adding a column to the Documents Library","Navigate to your Document Library https://&#60;designator&#62;.sharepoint.com/documentcenter/Documents or similar.",""],
["./adding-a-column-to-the-site-ro.html","Metadata &#62; Creating your own Metadata &#62; Adding a column to the site root","Navigate to the root of your Document center https://&#60;designator&#62;.sharepoint.com/documentcenter or similar.",""],
["./adding-a-single-sign-on-logo.html","CCH iFirm Integration Guide &#62; Single Sign-On &#62; Adding a Single Sign-on Logo","To add your own custom logo to your single sign-on application, you will need to:",""],
["./append-or-prepend.html","Scans &#62; The Controls &#62; Settings &#62; File Renaming &#62; Append or Prepend","This feature allows you to append or prefix your files with a word based on words found in the document:",""],
["./apply-metadata.html","Apply Metadata","Enter topic text here.",""],
["./assigning-users-and-groups.html","CCH iFirm Integration Guide &#62; Single Sign-On &#62; Assigning Users and Groups","Once you&#39;ve created your single sign-on application, you must now assign users and/or groups. Before getting started, you&#39;ll want to make note of ...",""],
["./automatic-metadata-columns.html","Metadata &#62; Automatic Metadata Columns","OnePractice allows the toggling of two settings in the HubOne Common AppSettings list in your SharePoint Document Center to automatically save Cli...",""],
["./basic-usage.html","Scans &#62; Basic Usage","If you have configured Scans to work with your scanner correctly, simply scan a document and the following screen will appear:",""],
["./categorising-emails-in-outlook.html","Mail &#62; Categorising Emails in Outlook","Mail will add a category &#8220;OnePractice&#8221; to each email it saves to SharePoint. This will appear as a blue box next to the email in your email client...",""],
["./cch-ifirm-integration-guide.html","CCH iFirm Integration Guide","This section details the integration between HubOne’s OnePractice&#8482; and CCH iFirm Practice Manager. ",""],
["./clear-all-settings.html","Scans &#62; The Controls &#62; Settings &#62; Clear All Settings","The Clear all settings button removes all settings.",""],
["./client-matching-rules.html","Scans &#62; The Controls &#62; Settings &#62; Client Matching Rules","Client Matching rules are the rules whereby Scans matches the Client to the document.",""],
["./client-search.html","Scans &#62; Basic Usage &#62; Manual Processing &#62; Edit Document Details &#62; Client Search","If Scans has been unable to identify the client in your scanned document or it has detected a different entity, you will need to search for the cl...",""],
["./clients.html","SharePoint Site &#62; Document Center &#62; Lists &#62; Clients","The Clients list contains information regarding clients in the practice management system and consists of the following fields:",""],
["./common-app-settings.html","Scans &#62; The Controls &#62; Settings &#62; Processing Settings &#62; Common App Settings","Common App Settings shows the configuration of your OnePractice environment.",""],
["./components.html","CCH iFirm Integration Guide &#62; Components","The required components for this integration are:  A Swagger Definition of the CCH iFirm API  Three Microsoft Flow Templates An Installa...",""],
["./connect-to-document-center.html","Mail Templates &#62; The Controls &#62; Connect to Document Center","Go here to enter your Office 365 credentials and your SharePoint Document Center site address.",""],
["./connect-to-product_name.html","Mail &#62; The Controls &#62; Connect to Document Center","Go here to enter your Office 365 credentials and your SharePoint Document Center site address.",""],
["./connecting.html","OnePracticeSync &#62; Connecting to CCH iFirm","The following procedure shows how to connect and configure your OnePractice Environment with CCH iFirm",""],
["./connection-icon.html","Scans &#62; The Controls &#62; Connection","The Connection Icon shows the Essential Connection Settings.",""],
["./contatcs.html","SharePoint Site &#62; Document Center &#62; Lists &#62; Contacts","A list of contacts is coming in a future release.",""],
["./content-organizer.html","SharePoint Site &#62; Document Center &#62; Content Organizer","The Content organizer allows content to be automatically filed based on metadata.",""],
["./controls.html","Scans &#62; The Controls","The following are controls in Scans:   Drag and Drop  Process History  Reprocess Documents Only  Refresh and Reprocess  S...",""],
["./create-new-email-template-dire.html","Mail Templates &#62; Creating Email Templates &#62; Create new email template directly from Outlook","Select New Email and create your template email content including adding any attachments you want to be included in the template.",""],
["./creating-a-shortcut-in-sharepo.html","CCH iFirm Integration Guide &#62; Single Sign-On &#62; Creating a Shortcut in SharePoint","Once you&#39;ve created the SSO application, you will find a link in the Waffle under All apps &#62; Other. However, you&#39;ll want this to be easier to a...",""],
["./creating-a-template.html","Templates &#62; Creating Templates","Templates can be created in 2 ways - Online or on your desktop. ",""],
["./creating-documents-merging-tem.html","Templates &#62; Creating Documents: Merging Templates with Client or Job Data","Select the template you wish to use by clicking either the Client or Job logo to the right of the document in order to merge with the relevant dat...",""],
["./creating-email-templates.html","Mail Templates &#62; Creating Email Templates","Manual creation through Outlook Email templates are stored in the same SharePoint Document Library as are templates used in the Templates applicat...",""],
["./creating-emails-adding-attachm.html","Mail Templates &#62; Creating Emails: Adding Attachments","Once you have selected a client from the list, you can add attachments to your email from within that client&#39;s Document Center folder before you s...",""],
["./creating-emails-merging-data-w.html","Mail Templates &#62; Creating Emails: Merging Templates with Client Data","Once you have selected the email template you wish to use, click the Merge with Client Icon next to the template name.",""],
["./creating-emails-merging-templa.html","Mail Templates &#62; Creating Emails: Merging Templates and Editing","Once you have selected the email template, click the Preview &#38; Edit button.",""],
["./creating-your-own-metadata.html","Metadata &#62; Creating your own Metadata","To create searchable metadata columns for your documents in SharePoint you will need to add a column to the site root and to the Documents library...",""],
["./credentials.html","Credentials","Enter your Office 365 credentials on this screen in order to use the app.",""],
["./custom-rule-builder.html","Scans &#62; The Controls &#62; Settings &#62; File Renaming &#62; Custom Rule Builder","The custom rule builder allows you to construct file names as you require. You can choose from or remove the following:",""],
["./delete.html","Scans &#62; Basic Usage &#62; Manual Processing &#62; Delete","Choosing Delete means the document will be deleted from your machine. You will need to scan the document again if you decide you want to process it.",""],
["./do-not-process.html","Scans &#62; Basic Usage &#62; Manual Processing &#62; Process Later","Choosing Process later means the document will be left in the folder until the Reprocess Documents Only or Refresh and Reprocess controls are clic...",""],
["./document-center.html","SharePoint Site &#62; Document Center","The Document Center site contains all client documents and templates.",""],
["./document-id-service.html","SharePoint Site &#62; Document Center &#62; Document ID Service","The Document ID Service is enabled and creates a unique ID for each document.",""],
["./document-summary.html","Scans &#62; Basic Usage &#62; Manual Processing &#62; Document Summary","The Document summary tells you information about the document including:",""],
["./documents-library.html","SharePoint Site &#62; Document Center &#62; Documents Library","The Documents Library is a standard SharePoint document library except:",""],
["./drag-and-drop.html","Templates &#62; The Controls &#62; Upload Templates","The Upload Templates button will open a new browser window and redirect you to the Modern Practice Templates folder. Here you can upload new Word ...",""],
["./drag-and-drop2.html","Scans &#62; The Controls &#62; Drag and Drop","Drag &#38; Drop allows you to drop searchable PDF files for the application to process.",""],
["./drop-off-library.html","SharePoint Site &#62; Document Center &#62; Content Organizer &#62; Drop Off Library","The Drop Off Library is used for documents that cannot be filed by the content organizer. You can configure who gets alerted to documents in the d...",""],
["./edit-document-details.html","Scans &#62; Basic Usage &#62; Manual Processing &#62; Edit Document Details","The Edit document details section allows you to edit details about the document as follows:",""],
["./edit-metadata.html","Scans &#62; Basic Usage &#62; Manual Processing &#62; Edit Metadata","The Edit metadata section allows you to edit contents of metadata. You can set metadata globally using the setting at Global MetaData. ",""],
["./enabling-single-sign-on.html","CCH iFirm Integration Guide &#62; Single Sign-On &#62; Enabling Single Sign-on","This topic describes how to enable Single Sign-on with Office 365 and CCH iFirm. The user will be able to automatically sign into CCH iFirm from w...",""],
["./essential-connection-settings.html","Scans &#62; The Controls &#62; Connection &#62; Essential Connection Settings","The Essential Connection Settings are the four items required to operate (at a minimum) Scans and are:",""],
["./exclude-clients.html","Scans &#62; The Controls &#62; Settings &#62; Client Matching Rules &#62; Exclude Clients","Many accounting practices have their firm included in their practice management system as one of the clients. To exclude that from matching, use t...",""],
["./export-and-import-settings.html","Scans &#62; The Controls &#62; Settings &#62; Import and Export Settings","The Import and Export Settings icons allow you to import and export all settings except user credentials:",""],
["./field-mapping.html","CCH iFirm Integration Guide &#62; Field Mapping","The following section details the default field mapping between CCH iFirm Practice Manager and SharePoint Lists.",""],
["./field-matching-options.html","Scans &#62; The Controls &#62; Settings &#62; Client Matching Rules &#62; Field Matching Options","Here you can choose which fields the app uses to match clients. Name is on by default, but you can also choose any field available. ",""],
["./field-tags.html","Templates &#62; Field Builder Options","There are 3 types of template fields: Standard, Custom and O365 User Info ",""],
["./file-renaming.html","Scans &#62; The Controls &#62; Settings &#62; File Renaming","File renaming allows the setting of the file name during upload based on rules.",""],
["./first-run.html","Scans &#62; Getting Started &#62; First Run","The first run of Scans will require you to enter the following:",""],
["./first-run2.html","First Run","The first run of Scan Doctor will require you to enter the following:",""],
["./getting-started.html","Templates &#62; Getting Started","Templates is installed by default on the homepage of your SharePoint Document Center.",""],
["./getting-started2.html","Scans &#62; Getting Started","To get started, follow the procedure below:   First Run",""],
["./global-metadata.html","Scans &#62; The Controls &#62; Settings &#62; Processing Settings &#62; Global MetaData","Global metadata allows you to set metadata for all filed scans to pre-determined values you set. This can be over-ridden in manual processing mode...",""],
["./help.html","Templates &#62; The Controls &#62; Help","A link to the software help website where you can download the complete Templates Documentation.",""],
["./help2.html","Mail Templates &#62; The Controls &#62; Help","Navigate to the software help website where you can download the complete Mail Templates Documentation.",""],
["./help3.html","Mail &#62; The Controls &#62; Help","Navigate to the software help website where you can download the complete Mail documentation.",""],
["./help4.html","Help","Navigate to the software help website where you can download the complete Scan Doctor documentation.",""],
["./how-to-guide2.html","Mail &#62; Getting Started","On first run, you will be presented with the Connect to Document Center popup window. ",""],
["./how-to-guide3.html","Mail Templates &#62; Getting Started","Mail Templates is accessed from Outlook Desktop client or Outlook Web App (OWA) from your browser by clicking the &#8220;New Email&#8221; button and then sele...",""],
["./how-to-ocr-a-pdf.html","How to OCR a PDF","Once you have configured Scan Doctor, simply drag and drop your PDF/s into the Input Folder. Scan Doctor will automatically detect the file/s with...",""],
["./hubone-common-app-settings.html","SharePoint Site &#62; Document Center &#62; Lists &#62; HubOne Common App Settings","The Common App Settings Table contains configuration for all OnePractice apps and is established via the Provisioning tool.",""],
["./implement-tools-and-practices.html","Implement tools and practices","Enter topic text here.",""],
["./important-notes-and-recommenda.html","Metadata &#62; Important Notes and Recommendations","These metadata columns will only become searchable after your site is re-indexed (this happens automatically every hour or so). ",""],
["./installation-and-configuration-flows.html","CCH iFirm Integration Guide &#62; Installation and Configuration of the Flows","In order to complete the connection between CCH iFirm Practice Manager and OnePractice, follow the procedures below::",""],
["./installation-guide.html","CCH iFirm Integration Guide &#62; Installation Guide","The installation takes place in three phases as follows:",""],
["./installation-of-onepractice.html","CCH iFirm Integration Guide &#62; Installation of OnePractice","The installation of OnePractice is documented in the Provisioning Guide. However, we have included some of those steps here, in order to provide y...",""],
["./installation.html","Scans &#62; Getting Started &#62; Installation","Connect to https://software.hubone.com/OnePracticeScans/ and click Download Application, or click here.",""],
["./installation2.html","Installation","Go to https://software.hubone.com/scandoctor/ and click Download ScanDoctor.",""],
["./integration-with-cch-ifirm.html","CCH iFirm Integration Guide &#62; Installation of the CCH iFirm Custom Connector","The following sections deal with the integration of a working and configured OnePractice solution with CCH iFirm Practice Manager.",""],
["./introduction.html","Introduction","Welcome to the User Guide for  OnePractice. This document contains the entire user information about the product, its configuration and vario...",""],
["./jobs.html","SharePoint Site &#62; Document Center &#62; Lists &#62; Jobs","A list of jobs is coming in a future release.",""],
["./license-onepractice.html","License OnePractice","Enter topic text here.",""],
["./licensing-onepractice.html","CCH iFirm Integration Guide &#62; Installation of OnePractice &#62; Part 3. Licensing OnePractice","You must first purchase licenses from your chosen Distributor. Once you have done so, you can follow the below instructions which will immediately...",""],
["./links-and-grid.html","SharePoint Site &#62; Root Site &#62; Links and Grid","Note: The configuration of a root sharepoint site is considered deprecated in this version and this section remains for customers with legacy impl...",""],
["./list-cache.html","Scans &#62; The Controls &#62; Settings &#62; Client Matching Rules &#62; List Cache","The list cache shows all the clients currently cached on your PC. If a client is missing, for example it was created recently, click Refresh Clien...",""],
["./lists.html","SharePoint Site &#62; Document Center &#62; Lists","Lists store key information that allow the various applications to function correctly. ",""],
["./mail-templates.html","Mail Templates","Enter topic text here.",""],
["./mail.html","Mail","Enter topic text here.",""],
["./making-columns-searchable.html","Metadata &#62; Making Columns Searchable","To enable search on your new columns they will have to be indexed.",""],
["./manual-processing.html","Scans &#62; Basic Usage &#62; Manual Processing","Manual processing mode is the default mode of operation for Scans. It allows for the verification of matching and other aspects before saving files.",""],
["./metadata-and-mail.html","Mail &#62; Metadata and Mail","For a detailed description of how to add metadata fields to your Document Center please see our Metadata Guide.",""],
["./metadata-and-product_name.html","Metadata &#62; Metadata and OnePractice","These custom metadata columns will now appear in Templates, Mail, Mail Templates and Scans after you hit the refresh buttons in each. ",""],
["./metadata-and-templates.html","Templates &#62; Metadata and Templates","Please see our full user guide on metadata fields.",""],
["./metadata.html","Metadata","This section covers:  What is metadata Why use metadata Automatic metadata columns Creating your own metadata Making columns searchable Metad...",""],
["./modern-practice-templates-fold.html","Templates &#62; Creating Templates &#62; Part 3. Saving Templates &#62; Modern Practice Templates folder &#62; Online","Creating the template via the Modern Practice Template folder means your template will be saved as go. ",""],
["./onepractice-mail-templates.html","Mail Templates","Mail Templates (not to be confused with Templates) is an Outlook add-in that allows you to use predefined email templates stored in SharePoint whi...",""],
["./onepractice-mail.html","Mail","Management of email messages has consistently been a difficult task. Ensuring emails and attachments to and from clients are saved and filed appro...",""],
["./onepractice-provisioning.html","About OnePractice","This section details the steps and procedures to deliver and deploy the OnePractice Version 6.8.#[Build.BuildID]# solution.",""],
["./onepractice-scans.html","Scans","Scans provides the means to significantly reduce the time spent by your staff filing scanned documents (or searchable PDF files) to client folders...",""],
["./onepractice-scansdoctor.html","OnePractice-ScansDoctor","Scan Doctor provides the means to convert non-OCR-readable pdf files that cannot be processed by OnePractice Scans into processable pdfs.",""],
["./onepractice-templates.html","Templates","Templates provides you with a central template store within your SharePoint Document Center so you can have a unified and consistent approach to w...",""],
["./onepracticesync.html","OnePracticeSync","OnePractice PracticeSync was released in September 2020 and replaces previous functionality either directly connecting to Xero Practice Manager or...",""],
["./onepracticesyncconfiguration.html","Provisioning &#62; OnePracticeSync Configuration","Once you have completed the provisioning of OnePractice, you then will need to integrate it with your chosen practice management system. Please fo...",""],
["./part-1_-creating-a-template.html","Templates &#62; Creating Templates &#62; Part 1. Creating New Templates","Creating from your Desktop Open Word or Excel on your PC. Move onto Part 2  Creating Online Open your preferred browser and navigate to your ...",""],
["./part-2_-adding-field-tags-to-y.html","Templates &#62; Creating Templates &#62; Part 2. Adding Field Tags to Templates","Add content to the document and style as desired. ",""],
["./pdf-processing-mode.html","Scans &#62; The Controls &#62; Settings &#62; Processing Settings &#62; PDF Processing Mode","PDF processing mode allows you to choose between automatic processing mode where files are automatically saved to the chosen client folder, or Man...",""],
["./post-provisioning.html","Provisioning &#62; Post Provisioning","Post provisioning, you can install Scans on computers which require it.",""],
["./preview-document.html","Scans &#62; Basic Usage &#62; Manual Processing &#62; Preview Document","The Preview document section allows you to simply preview and print the document.",""],
["./process-history.html","Scans &#62; The Controls &#62; Process History","Process History shows the last 100 successful and 50 unsuccessful documents. Click the tick to see the successful files and the cross to see unsuc...",""],
["./process-history2.html","Process History","View a record of all activity conducted during your current use of the app.",""],
["./processed-documents.html","Processed Documents","View all processed documents on this screen.   Successfully processed: The most recent 100 successfully processed documents or documents that...",""],
["./processing-settings.html","Scans &#62; The Controls &#62; Settings &#62; Processing Settings","The following settings are available under processing settings.",""],
["./product_name-migrator.html","Migrator","The Migrator App has been deprecated and its functionality replaced with the Microsoft SharePoint Migration Tool.",""],
["./product_name-provisioning.html","Provisioning","Provisioning involves the installation and configuration of OnePractice in an existing Office 365 environment. OnePractice requires a clean ShareP...",""],
["./product_name-sharepoint-site.html","SharePoint Site","OnePractice relies on a configured SharePoint Site to operate properly and the provisioning tool assists with its configuration. ",""],
["./provision-onepractice.html","Provision OnePractice","Enter topic text here.",""],
["./purchasing--licencing.html","Provisioning &#62; Purchasing &#38; Licencing","You must first purchase licenses from your chosen Distributor or resellser. Once you have done so, you can follow the below instructions which wil...",""],
["./recently-saved-documents.html","Templates &#62; The Controls &#62; Recently Saved Documents","View recently saved documents and links to those files and the folder it was saved to in your Document Center.",""],
["./refresh-and-reprocess.html","Scans &#62; The Controls &#62; Refresh and Reprocess","Refresh and reprocess performs the following tasks:",""],
["./refresh-clients--folders.html","Mail Templates &#62; The Controls &#62; Refresh Clients and Folders","Synchronize the application with any changes to your clients list or templates in your Modern Practice Templates folder.",""],
["./refresh-clients--folders2.html","Mail &#62; The Controls &#62; Refresh Clients and Folders","Synchronize the application with any changes to your clients list or your folder structure in SharePoint.",""],
["./refresh-list-frequency-setting.html","SharePoint Site &#62; Document Center &#62; Lists &#62; Refresh List Frequency Setting","All of the applications store a cache of all your clients and jobs in your local browser after its first load. This is to minimise loading time an...",""],
["./refresh.html","Templates &#62; The Controls &#62; Refresh","As Templates caches data locally in your internet browser to reduce network traffic and greatly speed up its functionality, it needs to be refresh...",""],
["./refreshing-your-client-and-jo2.html","Mail &#62; Refreshing Client and Job Lists Automatically","Mail stores a cache of all your clients and jobs in your local browser after its first load. This is to minimise loading time and to give you a mo...",""],
["./refreshing-your-client-and-job.html","Templates &#62; Refreshing Client and Job Lists Automatically","Templates stores a cache of all your clients and jobs in your local browser after its first load. This is to minimize loading time and to give you...",""],
["./release-notes.html","Introduction &#62; Release Notes","Version 6.8 Release Notes Welcome to the Release Notes for OnePractice 6.8. This release was authorised on 11 September 2020. This document contai...",""],
["./renaming-a-email-file.html","Mail &#62; Renaming an Email File","If you wish to change the name of the email being saved to your client’s folder, open the Save options section and enter a new name in the Rename ...",""],
["./renaming-attachments.html","Mail &#62; Renaming Attachments","Sometimes a client may send you attachments with obscure naming. This may be something that they recognise or was generated by their scanner. In t...",""],
["./reprocess-documents-only.html","Scans &#62; The Controls &#62; Reprocess Documents Only","Reprocess Documents only instructs the system to re-attempt any documents that have not been successfully processed, for example ones where Do not...",""],
["./root-site.html","SharePoint Site &#62; Root Site","Note: The configuration of a root SharePoint site is considered deprecated in this version and this section remains for customers with legacy impl...",""],
["./save-directly-into-modern-prac.html","Templates &#62; Creating Templates &#62; Part 3. Saving Templates &#62; Save directly into the Modern Practice Templates folder in the Document Center from Desktop","Within Word or Excel Desktop, go to File &#62; Save As.",""],
["./save-to-client.html","Scans &#62; Basic Usage &#62; Manual Processing &#62; Save to Client","Choosing Save to Client saves the document to the Client Folder in the Document Center and moves a copy to the SDMUploadCompleted folder under you...",""],
["./save-to-dropoff.html","Scans &#62; Basic Usage &#62; Manual Processing &#62; Save to DropOff","Choosing Save to DropOff saves to the DropOff Library. Users configured as DropOff Administrators will be alerted to these documents and will need...",""],
["./saving-attachments.html","Mail &#62; Saving Attachments","If your email has attachments and you wish to save them separately to the client folder as well, open the Attachments panel and select the Save at...",""],
["./saving-emails-to-client-folder.html","Mail &#62; Saving Emails to Client Folders","Basic saving At its most basic, the application is used to save emails to client folders in SharePoint. Select the desired client target from the ...",""],
["./saving-templates.html","Templates &#62; Creating Templates &#62; Part 3. Saving Templates","Templates are saved differently depending on how they are created:",""],
["./saving-to-subfolders.html","Mail &#62; Saving to Subfolders","If the chosen client target has subfolders under its root directory, by clicking on the subfolder icon (as shown below), the list of available fol...",""],
["./scans.html","Scans","Enter topic text here.",""],
["./set-default-metadata.html","Metadata &#62; Creating your own Metadata &#62; Setting default metadata","Navigate to your Document Library https://&#60;designator&#62;.sharepoint.com/documentcenter/Documents or similar.",""],
["./settings.html","Templates &#62; The Controls &#62; Settings","View essential settings retrieved from your SharePoint Document Center.",""],
["./settings2.html","Scans &#62; The Controls &#62; Settings","The Settings control allows you to configure various areas of the application. Clicking settings defaults to Processing Settings.",""],
["./settings3.html","Mail &#62; The Controls &#62; Settings","View your fixed settings in SharePoint.",""],
["./settings4.html","Settings","Use this screen to update your input folder, output folder and output configuration.",""],
["./single-sign-on.html","CCH iFirm Integration Guide &#62; Single Sign-On","This section describes how to enable single sign-on for CCH iFirm. ",""],
["./site-assets.html","SharePoint Site &#62; Root Site &#62; Site Assets","Note: The configuration of a root sharepoint site is considered deprecated in this version and this section remains for customers with legacy impl...",""],
["./site-pages.html","SharePoint Site &#62; Document Center &#62; Lists &#62; Site Pages","Site Pages is an internal SharePoint list. See Microsoft Documentation for more information.",""],
["./staff.html","SharePoint Site &#62; Document Center &#62; Lists &#62; Staff","A list of staff is coming in a future release. Note, however that OnePractice makes use of the link between staff and Office 365 users and will pr...",""],
["./standard-rules.html","Scans &#62; The Controls &#62; Settings &#62; File Renaming &#62; Standard Rules","Standard rules allows the following:    Append client name to the file name - Takes the existing file name and adds the client name to t...",""],
["./step-1-order-offfice-365-trial.html","CCH iFirm Integration Guide &#62; Installation of OnePractice &#62; Part 1: Order Office 365 Trial","In this procedure, you will be guided through creating an Office 365 Trial. Use the checklist in Installation of the CCH iFirm Connector to record...",""],
["./step-1_-install-and-configure-.html","CCH iFirm Integration Guide &#62; Installation of the CCH iFirm Custom Connector &#62; Part 1. Create Custom Connector","Step Instructions Screenshot 1 Navigate to PowerApps.  https://powerapps.com  Click Sign In.   2 Use your global administrator cred...",""],
["./step-2_-installation-of-onepra.html","CCH iFirm Integration Guide &#62; Installation of OnePractice &#62; Part 2. Installation Prerequisites","The following procedure details how to install OnePractice prerequisites.",""],
["./step-2_-installation-of-onepra_2.html","Provisioning &#62; Installation of OnePractice Prerequisites","The following procedure details how to install OnePractice prerequisites.",""],
["./step-2_-login-and-initialize-m.html","CCH iFirm Integration Guide &#62; Installation and Configuration of the Flows &#62; Part 1. Login and Initialise Microsoft Flow","The integration uses Microsoft Flow to connect CCH iFirm Practice Management data with the OnePractice apps. In order to make this work effectivel...",""],
["./step-3_-implement-flow-3.html","CCH iFirm Integration Guide &#62; Installation and Configuration of the Flows &#62; Part 2. Implement Flow #3","There are three Flow workflows to configure the integration with CCH iFirm Practice Manager. They are implemented in reverse order. The following ...",""],
["./step-4_-implement-flow-2.html","CCH iFirm Integration Guide &#62; Installation and Configuration of the Flows &#62; Part 3. Implement Flow #2","This process implements the second flow workflow required to enable the CCH iFirm Integration.",""],
["./step-4_-provisioning.html","CCH iFirm Integration Guide &#62; Installation of OnePractice &#62; Part 4. Provisioning","The following steps complete the installation of OnePractice.",""],
["./step-4_-provisioning_2.html","Provisioning &#62; Provisioning Process","The following steps complete the installation of OnePractice.",""],
["./step-5_-implement-flow-1.html","CCH iFirm Integration Guide &#62; Installation and Configuration of the Flows &#62; Part 4. Implement Flow #1","This is the procedure to implement the final flow and kick start the synchronisation.",""],
["./subfolders-in-the-document-cen.html","SharePoint Site &#62; Document Center &#62; Subfolders in the Document Center","Our applications utilise SharePoint&#39;s own search functionality to load subfolders from a client folder in your SharePoint Document Center. This al...",""],
["./suppliers.html","SharePoint Site &#62; Document Center &#62; Lists &#62; Suppliers","A list of suppliers is coming in a future release.",""],
["./tasks.html","SharePoint Site &#62; Document Center &#62; Lists &#62; Tasks","A list of tasks will be provided in a future version.",""],
["./template-field-builder.html","Templates &#62; The Controls &#62; Template Field Builder","Create Standard, Custom Prompt and O365 User Info fields that you can easily copy and paste into your Microsoft Office template file.",""],
["./templates.html","Templates","Enter topic text here.",""],
["./the-controls.html","Templates &#62; The Controls","The controls can be accessed via icons at the top of the application.",""],
["./the-controls2.html","Mail &#62; The Controls","There are five controls available at the top of the application.",""],
["./the-controls3.html","Mail Templates &#62; The Controls","There are four controls available at the top of the application.",""],
["./the-controls4.html","The Controls","The following are controls in Scan Doctor:  Credentials Processed Documents Settings Process History Help",""],
["./themes.html","SharePoint Site &#62; Root Site &#62; Themes","Note: The configuration of a root sharepoint site is considered deprecated in this version and this section remains for customers with legacy impl...",""],
["./update-theme.html","Mail Templates &#62; The Controls &#62; Update Theme","Synchronizes the application theme with your Office 365 theme.",""],
["./update-theme2.html","Mail &#62; The Controls &#62; Update Theme","Synchronize the application theme with your Office 365 theme.",""],
["./using-mail-templates-to-create.html","Mail Templates &#62; Creating Email Templates &#62; Creating new email templates from Outlook Web App (OWA)","Select New Email in Outlook and create your template email content including adding any attachments you want to be included in the template.",""],
["./using-onepractice-mail.html","Mail &#62; Using Mail","Mail is accessed from your email body in Outlook Desktop client or Outlook Web App (OWA) from your browser by clicking the Mail tab at the top of ...",""],
["./using-template-field-builder.html","Templates &#62; Using Template Field Builder","Standard Template Fields  The following steps show how to create a standard template field.  Select the type of field you want to use fr...",""],
["./verifying-a-template.html","Templates &#62; Verifying a Template","Once you have created your template, you should verify it against the rules used by the software. ",""],
["./welcome-topic.html","Introduction &#62; Welcome","OnePractice consists of a number of apps and a configuration of Microsoft SharePoint Online (part of Office 365 ) to assist accounting firms simpl...",""],
["./what-is-metadata_.html","Metadata &#62; What is Metadata?","Metadata is simply extra data used to describe your document. When we talk about metadata in the context of OnePractice, we are talking about addi...",""],
["./why-use-metadata_.html","Metadata &#62; Why use Metadata?","The extra data columns help us move away from traditional folder hierarchy structures and allow us to search for our documents based on sophistica...",""],
["./word-equivalency.html","Scans &#62; The Controls &#62; Settings &#62; Client Matching Rules &#62; Word Equivalency","Using word equivalency allows you to match abbreviations and other items.",""],
["./word-for-desktop--save-to-desk.html","Templates &#62; Creating Templates &#62; Part 3. Saving Templates &#62; Save to Desktop &#62; Upload to Modern Practice Templates in your Document Center","Within Word or Excel Desktop, go to File &#62; Save As.",""]];
